generate SSH key (Linux) or password (Linux/ Windows) for VMSS and store in Key Vault
Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset pull request #115
Opened 2024-12-29 13:53 UTC by MinHeinA

## Description

Add a feature to generate an SSH key (Linux) or password (Linux/ Windows) for VMSS and store it in Key Vault with examples for both Linux and Windows.

Please advise on ./avm pr-check minor linting check error "Failed to check ruleset; failed to check "azurerm_application_gateway.sku.name" rule: could not get partial content: main.authentication.tf:14,28-50: Attempt to get attribute from null value; This value is null, so it does not have any attributes., and 5 other diagnostic(s)"

Closes #96 

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [x] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-12-30 12:22 UTC, MinHeinA commented
Thank you, @chianw, for highlighting the race condition in newly added examples caused by a delay in the role assignment taking effect. Adding the depend on statement has fixed this issue.

2024-12-30 14:07 UTC, chianw commented
Hi @lonegunmanb are you able to advise on this linting error observed - https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/actions/runs/12546446918/job/34983703988?pr=115#step:3:619 

which does not make sense as there's application gateway resource in main.authentication.tf 

![image](https://github.com/user-attachments/assets/a8392751-b7a0-4a12-b2b8-0cc4a48e02e4)

2024-12-31 03:10 UTC, lonegunmanb requested changes
Thanks @MinHeinA for opening this pr! I've reviewed the changes and left some comments to fix the failed tflint rules and simplify the expressions, would you please take a look and have a double check on the logic? Thanks!

2024-12-31 03:10 UTC, lonegunmanb commented on main.authentication.tf
> +
Please add the following `locals` block here:

```hcl
locals {
  generate_key_vault_secret                                      = var.generate_admin_password_or_ssh_key && var.generated_secrets_key_vault_secret_config != null
  os_prifile_linux_configuration_disable_password_authentication = try(var.os_profile.linux_configuration.disable_password_authentication, true)
  os_profile_windows_configuration_null                          = try(var.os_profile.windows_configuration == null, true)
  use_password                                                   = !local.os_profile_windows_configuration_null || !local.os_prifile_linux_configuration_disable_password_authentication
}
```

2024-12-31 03:10 UTC, lonegunmanb commented on main.authentication.tf
> +  count = (((var.os_profile.windows_configuration != null) && (var.generate_admin_password_or_ssh_key == true)) || (((var.generate_admin_password_or_ssh_key == true) && (var.os_profile.linux_configur
We can simplify the expression to:

```hcl
count = var.generate_admin_password_or_ssh_key && local.use_password ? 1 : 0
```

2024-12-31 03:10 UTC, lonegunmanb commented on main.authentication.tf
> +  count = (((var.generate_admin_password_or_ssh_key == true) && (var.os_profile.windows_configuration != null) && (var.generated_secrets_key_vault_secret_config != null)) || ((var.generate_admin_pass
We can simplify the expression to:

```hcl
count = local.use_password && local.generate_key_vault_secret ? 1 : 0
```

2024-12-31 03:10 UTC, lonegunmanb commented on main.authentication.tf
> +  count = ((var.generate_admin_password_or_ssh_key == true) && (var.os_profile.linux_configuration != null) && (try(var.os_profile.linux_configuration.disable_password_authentication, false) == true)
We can simplify the expression to:

```hcl
count = var.generate_admin_password_or_ssh_key && !local.use_password ? 1 : 0
```

2024-12-31 03:10 UTC, lonegunmanb commented on main.authentication.tf
> +  count = ((var.generate_admin_password_or_ssh_key == true) && (var.os_profile.linux_configuration != null) && (try(var.os_profile.linux_configuration.disable_password_authentication, false) == true)
We can simplify this expression to:

```hcl
count = local.generate_key_vault_secret && !local.use_password ? 1 : 0
```

2024-12-31 03:12 UTC, lonegunmanb requested changes
@MinHeinA One more review comment.

2024-12-31 03:12 UTC, lonegunmanb commented on variables.tf
> +  description = "Set this value to true if the deployment should create a strong password for the admin user. If `os_type` is Linux, this will generate and store an SSH key as the default. However, s
Could we add `nullable = false` here?

2025-01-08 00:58 UTC, MinHeinA commented
@lonegunmanb also may I know why the linting error for application gateway occurred and how it was fixed by refactoring the code? Thank you

2025-02-28 17:52 UTC, terrymandin commented
@MinHeinA , thank you for creating this PR!  Sorry for the delay in merging it.  I have upgraded the providers and also applied some chore PRs.  Please merge the main branch updates into your PR.  Then I will test/merge.

2025-03-26 13:50 UTC, MinHeinA commented
@terrymandin updated PR to sync with main, updated terraform providers in examples and ran commit/PR checks with no errors

2025-03-27 02:33 UTC, merged